<?php

/**
 * PlugingbRememberMeToken
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gbRememberMe
 * @subpackage model
 * @author     Gabriel Birke <birke@d-scribe.de>
 * @version    SVN: $Id$
 */
abstract class PlugingbRememberMeToken extends BasegbRememberMeToken
{
  /**
   * Return true if the parameter token matches the stored token
   * 
   * @param string $token
   * @return boolean
   */
  public function checkTokenIsValid($token)
   {
     return $this->getToken() == $token;
   }
   
   /**
    * @param mixed $expires UNIX timestamp (integer) or YYYY-MM-DD HH:MM:SS 
    *        date string
    */
   public function setExpires($expires)
   {
    if(is_int($expires)) {
      $expires = date('Y-m-d H:i:s', $expires);
    }
    $this->_set('expires', $expires);
   }

}